services:
  redis:
    container_name: api-redis
    image: redis:6.2-alpine

  api1:
    container_name: api-1
    image: local/ws_api:2
    build: .
    volumes:
      - ./app:/api/app
    environment:
      - HOST=api1
      - PORT=5001
      - REDIS=redis://redis/0
    ports:
      - 5001:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  api2:
    container_name: api-2
    image: local/ws_api:2
    build: .
    volumes:
      - ./app:/api/app
    environment:
      - HOST=api2
      - PORT=5002
      - REDIS=redis://redis/0
    ports:
      - 5002:5002
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  nginx:
    container_name: api-nginx
    image: nginx:1.24-alpine
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/api.conf
    ports:
      - 8000:80
      - 8010:8010
    depends_on:
      - api1
      - api2

networks:
  default:
    name: api-net
    driver: bridge
    enable_ipv6: false
